spring.application.name=srms-web
spring.datasource.url=jdbc:sqlite:/path/to/your.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000